In [1]:
import numpy as np

In [2]:
sx = np.array([[0, 1],[ 1, 0]])
sy = np.array([[0, -1j],[1j, 0]])
sz = np.array([[1, 0],[0, -1]])


In [4]:
sxx = np.kron(sx, sx)
syy = np.kron(sy, sy)
szz = np.kron(sz, sz)

In [5]:
def cmtr(a, b):
    return np.dot(a, b) - np.dot(b,a)

In [6]:
cmtr(sx, sy)

array([[ 0.+2.j,  0.+0.j],
       [ 0.+0.j,  0.-2.j]])

In [7]:
cmtr(sxx, syy)

array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j]])

In [8]:
np.dot(sxx, syy)

array([[-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.+0.j]])

In [9]:
np.kron(np.dot(sx, sy), np.dot(sx, sy))

array([[-1.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  1.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j, -1.-0.j]])

In [10]:
np.dot(sx, sy)

array([[ 0.+1.j,  0.+0.j],
       [ 0.+0.j,  0.-1.j]])

In [11]:
np.dot(sy, sx)

array([[ 0.-1.j,  0.+0.j],
       [ 0.+0.j,  0.+1.j]])

In [13]:
np.dot(np.dot(sx, sy), sx)

array([[ 0.+0.j,  0.+1.j],
       [ 0.-1.j,  0.+0.j]])

In [14]:
sy

array([[ 0.+0.j, -0.-1.j],
       [ 0.+1.j,  0.+0.j]])