In [1]:
import numpy as np

In [2]:
sx = np.array([[0, 1],[ 1, 0]])
sy = np.array([[0, -1j],[1j, 0]])
sz = np.array([[1, 0],[0, -1]])

In [3]:
a0 = sz
a1 = sx
b0 = 1/np.sqrt(2) * (sx + sz)
b1 = 1/np.sqrt(2) * (sx - sz)

In [4]:
S = np.kron(a0, b0) - np.kron(a1, b0) - np.kron(a0, b1) - np.kron(a1, b1)

In [5]:
print(S)

[[ 1.41421356  0.          0.         -1.41421356]
 [ 0.         -1.41421356 -1.41421356  0.        ]
 [ 0.         -1.41421356 -1.41421356  0.        ]
 [-1.41421356  0.          0.          1.41421356]]


In [6]:
S_rew = np.sqrt(2) * (np.kron(sz,sz) - np.kron(sx, sx))

In [7]:
print(S_rew)

[[ 1.41421356  0.          0.         -1.41421356]
 [ 0.         -1.41421356 -1.41421356  0.        ]
 [ 0.         -1.41421356 -1.41421356  0.        ]
 [-1.41421356  0.          0.          1.41421356]]


In [11]:
dn = np.array([1, 0])
up = np.array([0, 1])

upup = np.kron(up, up)
updn = np.kron(up, dn)
dnup = np.kron(dn, up)
dndn = np.kron(dn, dn)

In [13]:
CNOT = np.array([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0]
    ])

In [20]:
phi_p = 1/np.sqrt(2) * (upup + dndn)
phi_m = 1/np.sqrt(2) * (upup - dndn)
psi_p = 1/np.sqrt(2) * (updn + dnup)
psi_m = 1/np.sqrt(2) * (updn - dnup)

In [23]:
F = 0.25

W_F = F * np.kron(psi_m, psi_m.T) + (1-F)/3 * (np.kron(psi_p, psi_p.T) + np.kron(phi_p, phi_p.T) + np.kron(phi_m, phi_m.T))

In [24]:
W_F

array([ 0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.25,  0.  ,  0.  ,  0.  ,
        0.  ,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,  0.25])

In [41]:
np.dot(psi_m, psi_m.reshape(4,1))

array([ 1.])

In [38]:
psi_m.reshape(4,1)

array([[ 0.        ],
       [-0.70710678],
       [ 0.70710678],
       [ 0.        ]])