In [41]:
import numpy as np

In [108]:
# pauli matrices

sx = np.array([[0, 1],[ 1, 0]])
sy = np.array([[0, -1j],[1j, 0]])
sz = np.array([[1, 0],[0, -1]])
si = np.eye(2)

z0 = np.array([1, 0])
z1 = np.array([0, 1])

x0 = np.array([1, -1]) / np.sqrt(2)
x1 = np.array([1, 1]) / np.sqrt(2)

y0 = np.array([1, 1j]) / np.sqrt(2)
y1 = np.array([1, -1j]) / np.sqrt(2)

bstates = {
    'z0': z0,
    'z1': z1,
    'x0': x0,
    'x1': x1,
    'y0': y0,
    'y1': y1
}

In [62]:
def R(axis, angle):
    axis = np.array(axis).reshape(3)
    return np.cos(angle/2) * si - 1j * np.sin(angle/2) * np.dot(np.array([sx, sy, sz]).T, axis)

In [151]:
def check_rotation(axis, angle, input_state, expected_state):
    print("%s rotated by %.2f pi over axis %s" % (input_state, angle/np.pi, axis))
    
    output_state = np.dot(R(axis, angle), bstates[input_state])
    print("output state       : %s" % output_state)
    raw_overlap = output_state / bstates[expected_state]
    print("comparison to expected state: %s" % expected_state)
    print("raw overlap     : %s" % (raw_overlap))
    print("avg raw overlap : %s" % str(np.mean(raw_overlap)))
    print("absval avg raw o: %f" % (np.abs(np.mean(raw_overlap))))
    print("angle avg raw o : %.2f pi" % (np.angle(np.mean(raw_overlap)) / np.pi))

In [98]:
print("z0 rotated by pi/2 over +y-ax")
z0_rot_y = np.dot(R([0, 1, 0], np.pi/2), z0)
print(z0_rot_y)
print(z0_rot_y / x0)

print("z1 rotated by pi/2 over +y-ax")
z1_rot_y = np.dot(R([0, 1, 0], np.pi/2), z1)
print(z1_rot_y)
print(z1_rot_y / x1)

z0 rotated by pi/2 over +y-ax
[ 0.70710678+0.j -0.70710678+0.j]
[ 1.+0.j  1.-0.j]
z1 rotated by pi/2 over +y-ax
[ 0.70710678+0.j  0.70710678+0.j]
[ 1.+0.j  1.+0.j]


In [101]:
print("z0 rotated by pi/2 over +x-ax")
z0_rot_x = np.dot(R([1, 0, 0], np.pi/2), z0)
print(z0_rot_x)
print(z0_rot_x / y1)

print("z1 rotated by pi/2 over +x-ax")
z1_rot_x = np.dot(R([1, 0, 0], np.pi/2), z1)
print(z1_rot_x)
print(z1_rot_x / y0)

z0 rotated by pi/2 over +x-ax
[ 0.70710678+0.j          0.00000000-0.70710678j]
[ 1.+0.j  1.+0.j]
z1 rotated by pi/2 over +x-ax
[ 0.00000000-0.70710678j  0.70710678+0.j        ]
[ 0.-1.j  0.-1.j]


In [102]:
print("z0 rotated by pi/2 over -x-ax")
z0_rot_mx = np.dot(R([-1, 0, 0], np.pi/2), z0)
print(z0_rot_mx)
print(z0_rot_mx / y0)

print("z1 rotated by pi/2 over -x-ax")
z1_rot_mx = np.dot(R([-1, 0, 0], np.pi/2), z1)
print(z1_rot_mx)
print(z1_rot_mx / y1)

z0 rotated by pi/2 over -x-ax
[ 0.70710678+0.j          0.00000000+0.70710678j]
[ 1.+0.j  1.+0.j]
z1 rotated by pi/2 over -x-ax
[ 0.00000000+0.70710678j  0.70710678+0.j        ]
[ 0.+1.j -0.+1.j]


## Rotations over +y

In [125]:
check_rotation([0, 1, 0], np.pi/2, 'z0', 'x0')

z0 rotated by 0.50 pi over axis [0, 1, 0]
output state       : [ 0.70710678+0.j -0.70710678+0.j]
comparison to expected state: x0
raw overlap     : [ 1.+0.j  1.-0.j]
avg raw overlap : (1+0j)
absval avg raw o: 1.000000


In [126]:
check_rotation([0, 1, 0], np.pi/2, 'z1', 'x1')

z1 rotated by 0.50 pi over axis [0, 1, 0]
output state       : [ 0.70710678+0.j  0.70710678+0.j]
comparison to expected state: x1
raw overlap     : [ 1.+0.j  1.+0.j]
avg raw overlap : (1+0j)
absval avg raw o: 1.000000


## Rotations over +x

In [115]:
check_rotation([1, 0, 0], np.pi/2, 'z0', 'y1')

z0 rotated by 0.50 pi over axis [1, 0, 0]
output state       : [ 0.70710678+0.j          0.00000000-0.70710678j]
comparison to expected state: y1
raw overlap     : [ 1.+0.j  1.+0.j]
avg raw overlap : (1+0j)
absval avg raw o: 1.000000


In [116]:
check_rotation([1, 0, 0], np.pi/2, 'z1', 'y0')

z1 rotated by 0.50 pi over axis [1, 0, 0]
output state       : [ 0.00000000-0.70710678j  0.70710678+0.j        ]
comparison to expected state: y0
raw overlap     : [ 0.-1.j  0.-1.j]
avg raw overlap : -1j
absval avg raw o: 1.000000


## Rotations over -x

In [121]:
check_rotation([-1, 0, 0], np.pi/2, 'z0', 'y0')

z0 rotated by 0.50 pi over axis [-1, 0, 0]
output state       : [ 0.70710678+0.j          0.00000000+0.70710678j]
comparison to expected state: y0
raw overlap     : [ 1.+0.j  1.+0.j]
avg raw overlap : (1+0j)
absval avg raw o: 1.000000


In [122]:
check_rotation([-1, 0, 0], np.pi/2, 'z1', 'y1')

z1 rotated by 0.50 pi over axis [-1, 0, 0]
output state       : [ 0.00000000+0.70710678j  0.70710678+0.j        ]
comparison to expected state: y1
raw overlap     : [ 0.+1.j -0.+1.j]
avg raw overlap : 1j
absval avg raw o: 1.000000


In [138]:
((y0 - y1) / np.sqrt(2))

array([ 0.+0.j,  0.+1.j])

In [144]:
(-1j * y0 + y1) / np.sqrt(2)

array([ 0.5-0.5j,  0.5-0.5j])

In [149]:
np.exp(-1j * np.pi/4) * x0

array([ 0.5-0.5j, -0.5+0.5j])

In [148]:
(y0 - 1j * y1) / np.sqrt(2)

array([ 0.5-0.5j, -0.5+0.5j])

## Rotations of x basis states over +x

In [160]:
check_rotation([1, 0, 0], np.pi/2, 'x0', 'x0')

x0 rotated by 0.50 pi over axis [1, 0, 0]
output state       : [ 0.5+0.5j -0.5-0.5j]
comparison to expected state: x0
raw overlap     : [ 0.70710678+0.70710678j  0.70710678+0.70710678j]
avg raw overlap : (0.707106781187+0.707106781187j)
absval avg raw o: 1.000000
angle avg raw o : 0.25 pi


In [161]:
check_rotation([1, 0, 0], np.pi/2, 'x1', 'x1')

x1 rotated by 0.50 pi over axis [1, 0, 0]
output state       : [ 0.5-0.5j  0.5-0.5j]
comparison to expected state: x1
raw overlap     : [ 0.70710678-0.70710678j  0.70710678-0.70710678j]
avg raw overlap : (0.707106781187-0.707106781187j)
absval avg raw o: 1.000000
angle avg raw o : -0.25 pi


## Rotations of x basis states over -x

In [167]:
check_rotation([-1, 0, 0], np.pi/2, 'x0', 'x0')

x0 rotated by 0.50 pi over axis [-1, 0, 0]
output state       : [ 0.5-0.5j -0.5+0.5j]
comparison to expected state: x0
raw overlap     : [ 0.70710678-0.70710678j  0.70710678-0.70710678j]
avg raw overlap : (0.707106781187-0.707106781187j)
absval avg raw o: 1.000000
angle avg raw o : -0.25 pi


In [166]:
check_rotation([-1, 0, 0], np.pi/2, 'x1', 'x1')

x1 rotated by 0.50 pi over axis [-1, 0, 0]
output state       : [ 0.5+0.5j  0.5+0.5j]
comparison to expected state: x1
raw overlap     : [ 0.70710678+0.70710678j  0.70710678+0.70710678j]
avg raw overlap : (0.707106781187+0.707106781187j)
absval avg raw o: 1.000000
angle avg raw o : 0.25 pi


In [171]:
np.exp(-1j * np.pi/2)

(6.123233995736766e-17-1j)

In [173]:
np.exp(-1j * 0.75 * np.pi) + np.exp(1j * 0.25 * np.pi)

(1.1102230246251565e-16-1.1102230246251565e-16j)